#!/bin/bash

# Preapare docker file
rm -rf ./Dockerfile 
cp ./Dockerfile.prod ./Dockerfile 

# Prepare env file
rm -rf ./env.js
cp ./env.stg.js ./env.js

# Build and run
docker build --no-cache -t nextjs:init . && docker run -p 3000:3000 nextjs:init
