#!/bin/bash

# Preapare docker file
rm -rf ./Dockerfile 
cp ./Dockerfile.dev ./Dockerfile 

# Prepare env file
rm -rf ./next.config.js
cp ./next.config.dev.js ./next.config.js

# Build and run
docker build --no-cache -t nextjs:init . && docker run -p 3000:3000 nextjs:init
