FROM node:10

WORKDIR /usr/src/app

# Folders
COPY components ./components
COPY pages ./pages
COPY utils ./utils

# Files
COPY env.js ./
COPY package*.json ./
COPY server.js ./
COPY yarn.lock ./
COPY next.config.js ./
COPY .babelrc ./

RUN yarn install

RUN yarn build

EXPOSE 3000

CMD yarn start